import builtins
from collections.abc import Callable, Iterator
from os import PathLike

# raises the exceptions in durastream.errors

class DurableStream:
    @property
    def name(self) -> str: ...
    @property
    def content_type(self) -> str: ...
    @property
    def next_offset(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    @property
    def writable(self) -> bool: ...
    def append(self, payload: bytes) -> int: ...
    def append_many(self, payloads: list[bytes]) -> int: ...
    def read(self, offset: int = 0, end: int | None = None) -> list[bytes]: ...
    def subscribe(self, offset: int = 0) -> Iterator[bytes]: ...
    def close(self) -> None: ...
    def add_listener(self, callback: Callable[[], object]) -> int: ...
    def remove_listener(self, id: int) -> bool: ...

class Store:
    def __init__(self, root: str | PathLike[str]) -> None: ...
    @property
    def root(self) -> str: ...
    def create(self, name: str, content_type: str | None = None) -> DurableStream: ...
    def open(self, name: str) -> DurableStream: ...
    def delete(self, name: str) -> None: ...
    def list(self) -> builtins.list[str]: ...
    def close(self) -> None: ...

def to_token(offset: int) -> str: ...
def from_token(token: str, next_offset: int) -> int: ...
